table Brand_Table
	lineageTag: b5202f8f-4712-4288-841e-ed818c612d85

	column 'Brand (Key)'
		dataType: string
		lineageTag: c81f6762-3d11-4e81-9588-89c1e4d91f9a
		summarizeBy: none
		sourceColumn: Brand (Key)
		sortByColumn: 'Sort Order'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: string
		lineageTag: 622e6335-48e6-4970-843b-5be3deaaea62
		summarizeBy: none
		sourceColumn: Sort Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Short Name'
		dataType: string
		lineageTag: 47a9fc9b-4334-4c14-92eb-565a42ae584e
		summarizeBy: none
		sourceColumn: Short Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Material Group (Key)'
		dataType: string
		lineageTag: 42280334-3905-4c5d-bcd6-d01cc5f977fd
		summarizeBy: none
		sourceColumn: Material Group (Key)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Innovation?
		dataType: string
		lineageTag: 1c7c7e9e-6150-4d9c-88e0-f323a4ac0eda
		summarizeBy: none
		sourceColumn: Innovation?

		annotation SummarizationSetBy = Automatic

	column 'New Categ'
		dataType: string
		lineageTag: 18b7c7fa-c05a-4a94-a386-ffd044927c98
		summarizeBy: none
		sourceColumn: New Categ

		annotation SummarizationSetBy = Automatic

	column 'New Categ Other'
		dataType: string
		lineageTag: 9fc3c0c5-1143-4684-bc09-677ce3fd71a1
		summarizeBy: none
		sourceColumn: New Categ Other

		annotation SummarizationSetBy = Automatic

	column Column1
		dataType: string
		lineageTag: ed72b93f-3507-4023-a393-db0e15f083c2
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition Brand_Table = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Stk Cvg_Weekly Files\Mapping\Stock_Coverage_Mapping.xlsx"), null, true),
				    Brand_Table_Table = Source{[Item="Brand_Table",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(Brand_Table_Table,"T","Innovation",Replacer.ReplaceText,{"Innovation?"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Regular",Replacer.ReplaceValue,{"Innovation?"})
				in
				    #"Replaced Value1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

