table Week_Num
	lineageTag: 0f549ee3-3fbf-4c3c-8d02-21a4d3811cca

	column 'Week_Num (Key)'
		dataType: string
		lineageTag: e69eaf0b-1657-4ab4-89be-2d87b049cc8f
		summarizeBy: none
		sourceColumn: Week_Num (Key)
		sortByColumn: Sort

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Source_Name
		dataType: string
		lineageTag: eb8903dd-4d44-4deb-aad6-a9bdeed4e8af
		summarizeBy: none
		sourceColumn: Source_Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Num (Key)'
		dataType: string
		lineageTag: e6230993-0f95-44e4-9ce4-ff7232be3b5c
		summarizeBy: none
		sourceColumn: Num (Key)
		sortByColumn: Sort

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 4cd5c964-e2fc-4d94-a468-0243bc78e175
		summarizeBy: sum
		sourceColumn: Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mon_Link
		dataType: string
		lineageTag: d59e21cf-ca43-48ea-9c57-bf8360f905f3
		summarizeBy: none
		sourceColumn: Mon_Link

		annotation SummarizationSetBy = Automatic

	column W#
		dataType: string
		lineageTag: f568205b-13e7-42ca-a9f5-133b8b4e9572
		summarizeBy: none
		sourceColumn: W#

		annotation SummarizationSetBy = Automatic

	partition Week_Num = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Stk Cvg_Weekly Files\Mapping\Stock_Coverage_Mapping.xlsx"), null, true),
				    Week_Num_Table = Source{[Item="Week_Num",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Week_Num_Table,{{"Sort", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Week_Num (Key)", "Week_Num (Key) - Copy"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "Week_Num (Key) - Copy", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Week_Num (Key) - Copy.1", "Week_Num (Key) - Copy.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Week_Num (Key) - Copy.1", type text}, {"Week_Num (Key) - Copy.2", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Week_Num (Key) - Copy.1", "W#"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Week_Num (Key) - Copy.2"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

