table MonthWeek
	lineageTag: 47e673cf-746e-4b73-afe8-e23d08712b72

	column Month
		dataType: string
		lineageTag: e4f27822-a46c-480d-8831-9975c21bb6d1
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: c812dd8e-6738-42a9-b167-fcdf43d46b93
		summarizeBy: none
		sourceColumn: Week
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 836c97e1-f7d9-41c2-9b0f-f408e06a33e6
		summarizeBy: sum
		sourceColumn: Sort

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition MonthWeek = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Stk Cvg_Weekly Files\Mapping\Stock_Coverage_Mapping.xlsx"), null, true),
				    MonthWeek_Table = Source{[Item="MonthWeek",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(MonthWeek_Table,{{"Month", type text}, {"Week", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

