table SessionTable
	lineageTag: 99cd3eaa-95a2-418c-861d-3e9eebf1243c

	column Session
		dataType: string
		lineageTag: 1445a936-54a2-4b5b-a2c2-53eadefdd2fb
		summarizeBy: none
		sourceColumn: Session

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 473f433b-026e-41ac-84a0-9132fcc2edc4
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition SessionTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCjZU0lEyVIrVATKNgEwjCNMYyDRWio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Session = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Session", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

