table SFA_Comment_GAC
	lineageTag: a003bdec-2e10-499f-bc80-b781154d3a55

	column Mon
		dataType: string
		lineageTag: 5771a075-93b1-46bc-9375-2f1ae8e3bf98
		summarizeBy: none
		sourceColumn: Mon

		annotation SummarizationSetBy = Automatic

	column 'Lag Month2'
		dataType: string
		lineageTag: ebda53c5-053b-47f4-b43d-054b0cf5ea3c
		summarizeBy: none
		sourceColumn: Lag Month2

		annotation SummarizationSetBy = Automatic

	column 'APO Location'
		dataType: string
		lineageTag: 19a7dda9-acce-4a4b-bcaf-3d0782ae949e
		summarizeBy: none
		sourceColumn: APO Location

		annotation SummarizationSetBy = Automatic

	column 'Commercial Ref.'
		dataType: string
		lineageTag: 3021dba3-dc29-41a1-a36e-b3c86e5c1953
		summarizeBy: none
		sourceColumn: Commercial Ref.

		annotation SummarizationSetBy = Automatic

	column Desc
		dataType: string
		lineageTag: c6e68404-78f9-4798-a7fa-2b3daf48ff18
		summarizeBy: none
		sourceColumn: Desc

		annotation SummarizationSetBy = Automatic

	column 'Abs Delta on Order_CR'
		dataType: double
		lineageTag: 3a38e409-5d42-4b9b-b2bc-5225dd224afc
		summarizeBy: sum
		sourceColumn: Abs Delta on Order_CR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Driver
		dataType: string
		lineageTag: 103e7fcd-43b0-4e2e-b934-c53960b778f8
		summarizeBy: none
		sourceColumn: Driver

		annotation SummarizationSetBy = Automatic

	column Comment
		dataType: string
		lineageTag: 893a75de-d843-4c36-bda8-a593fa5be56f
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = Automatic

	column TableDriver
		dataType: string
		lineageTag: 17298686-9ab4-40f0-a40f-e0936076917d
		summarizeBy: none
		sourceColumn: TableDriver

		annotation SummarizationSetBy = Automatic

	column 'Clean Name'
		dataType: string
		lineageTag: 3433721c-32d5-4e13-9c5c-dd9358f6d49a
		summarizeBy: none
		sourceColumn: Clean Name

		annotation SummarizationSetBy = Automatic

	column Detail
		dataType: string
		lineageTag: 7def3004-e819-47b0-a59c-14966a8d5e5a
		summarizeBy: none
		sourceColumn: Detail

		annotation SummarizationSetBy = Automatic

	column 'Clean Name x2'
		dataType: string
		lineageTag: c4e99310-84ff-4636-b931-b09bafee9ce6
		summarizeBy: none
		sourceColumn: Clean Name x2

		annotation SummarizationSetBy = Automatic

	partition SFA_Comment_GAC = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Shared Files\Monthly Slides.xlsx"), null, true),
				    Table4_Table = Source{[Item="Table4",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table4_Table,{{"Mon", type text}, {"Lag Month2", type text}, {"APO Location", type text}, {"Material Group", type text}, {"Commercial Ref.", type text}, {"Desc", type text}, {"Channel", type text}, {"Forecast - Monday", type number}, {"Order", type number}, {"BIAS% on Order", type number}, {"SFA % on Order_CR", type number}, {"Abs Delta on Order_CR", type number}, {"MAPE % on Order_CR", type number}, {"Driver", type text}, {"Comment", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Lower Gulf","Other Lower Gulf",Replacer.ReplaceText,{"APO Location"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"Material Group", "Channel", "Forecast - Monday", "Order", "BIAS% on Order", "SFA % on Order_CR", "MAPE % on Order_CR"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Abs Delta on Order_CR", Order.Descending}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Sorted Rows", "Driver", "Driver - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Driver - Copy", "TableDriver"}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Renamed Columns","Activity Phasing","Phasing",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Alternative","Altern.",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Baseline","Base",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Arbitrage","Arbit.",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Innovation","Innov.",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Seasonal / Activity ","Seasonal",Replacer.ReplaceText,{"TableDriver"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Others","Other",Replacer.ReplaceText,{"TableDriver"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value7", each true),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Filtered Rows1", "Desc", "Desc - Copy"),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Duplicated Column1",{{"Desc - Copy", Text.Proper, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Capitalized Each Word", "Desc - Copy", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Desc - Copy.1", "Desc - Copy.2", "Desc - Copy.3"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Desc - Copy.1", type text}, {"Desc - Copy.2", type text}, {"Desc - Copy.3", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"Desc - Copy.2", "Desc - Copy.3"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Removed Columns1","<(>&<)>","&",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Wcp","",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9"," Ja","",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","Kinder","K.",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Nutella","N.",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","Bueno","Bue",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","Biscuits","Bisc",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","Schokobons","Schokb.",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","Nut & Go","Nut&Go",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","Chocolate","Choc.",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","Nut","N",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","Rocher","Roch",Replacer.ReplaceText,{"Desc - Copy.1"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value19",{{"Desc - Copy.1", "Clean Name"}}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Renamed Columns1"," Isr 17","",Replacer.ReplaceText,{"Clean Name"}),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Replaced Value20", "APO Location", "APO Location - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column2",{{"APO Location - Copy", "Detail"}}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Renamed Columns2","Saudi Arabia","KSA",Replacer.ReplaceText,{"Detail"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","Dubai","DXB",Replacer.ReplaceText,{"Detail"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","Other Lower Gulf","LGI",Replacer.ReplaceText,{"Detail"}),
				    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","Kuwait","KWT",Replacer.ReplaceText,{"Detail"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value24", "Clean Name x2", each [Clean Name]&[Detail]&" "&[Comment]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom",{{"Clean Name x2", type text}}),
				    #"Replaced Value25" = Table.ReplaceValue(#"Changed Type2","Saudi Arabia","GAC (Gulf)",Replacer.ReplaceText,{"APO Location"}),
				    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","Kuwait","GAC (Gulf)",Replacer.ReplaceText,{"APO Location"}),
				    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","Dubai","GAC (Gulf)",Replacer.ReplaceText,{"APO Location"}),
				    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","Other Lower Gulf","GAC (Gulf)",Replacer.ReplaceText,{"APO Location"})
				in
				    #"Replaced Value28"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

