table profile
	lineageTag: dbd244a6-eafd-4c26-821c-b4ba386b4ac5

	column symbol
		dataType: string
		lineageTag: ed2d00e9-e241-49ae-96c6-f512e4487786
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6e2db527-0c1e-40ca-80e4-679881184757
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column mktCap
		dataType: int64
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d3ddc683-2491-4d9c-a712-dea459e71336
		summarizeBy: sum
		sourceColumn: mktCap

		annotation SummarizationSetBy = Automatic

	column companyName
		dataType: string
		lineageTag: e441e6b9-0cf3-4f32-ac17-46aa4f830773
		summarizeBy: none
		sourceColumn: companyName

		annotation SummarizationSetBy = Automatic

	column exchange
		dataType: string
		lineageTag: 9eacf286-1b32-498a-887e-2d79cac97457
		summarizeBy: none
		sourceColumn: exchange

		annotation SummarizationSetBy = Automatic

	column exchangeShortName
		dataType: string
		lineageTag: 479b88f8-7933-4e3e-be03-14501739f4dc
		summarizeBy: none
		sourceColumn: exchangeShortName

		annotation SummarizationSetBy = Automatic

	column industry
		dataType: string
		lineageTag: 76141037-a249-4355-a081-6635e70d0bef
		summarizeBy: none
		sourceColumn: industry

		annotation SummarizationSetBy = Automatic

	column website
		dataType: string
		lineageTag: 52af5bb9-7480-42d4-a7bb-cff8ebf57c25
		summarizeBy: none
		sourceColumn: website

		annotation SummarizationSetBy = Automatic

	column ceo
		dataType: string
		lineageTag: 553794e9-6296-48a4-a125-fabdd18d7f9e
		summarizeBy: none
		sourceColumn: ceo

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: c1208500-8843-402e-a168-99baf6a69349
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column fullTimeEmployees
		dataType: int64
		formatString: 0
		lineageTag: 9d776be7-f11e-4143-8455-f7313094ad66
		summarizeBy: sum
		sourceColumn: fullTimeEmployees

		annotation SummarizationSetBy = Automatic

	column image
		dataType: string
		lineageTag: f8e1649c-951b-4497-b888-e540fb376bf7
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: image

		annotation SummarizationSetBy = Automatic

	column isEtf
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6944e13c-d76d-4595-9cf2-21254e6fd4dc
		summarizeBy: none
		sourceColumn: isEtf

		annotation SummarizationSetBy = Automatic

	column companyFullName
		dataType: string
		lineageTag: 7be63e24-fa3e-4dc4-8c2e-4e5bd23bce3c
		summarizeBy: none
		sourceColumn: companyFullName

		annotation SummarizationSetBy = Automatic

	column eps
		dataType: double
		lineageTag: 7c389b69-dd97-4659-a45f-0d01350a8615
		summarizeBy: sum
		sourceColumn: eps

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pe
		dataType: double
		lineageTag: 02b8e39c-942b-419d-a95e-95f46ba54fc0
		summarizeBy: sum
		sourceColumn: pe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 52WeekHigh
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 31c22f32-ca1d-4c6f-91c9-a95a9021543b
		summarizeBy: sum
		sourceColumn: 52WeekHigh

		annotation SummarizationSetBy = Automatic

	column 52WeekLow
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: dfb9764b-e008-4445-8ff2-62b6803cbbf8
		summarizeBy: sum
		sourceColumn: 52WeekLow

		annotation SummarizationSetBy = Automatic

	column close
		dataType: double
		lineageTag: 2baff969-5c5d-4569-8458-aa3d328921bb
		summarizeBy: sum
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column change
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8091cbbb-e3e5-4512-8c90-e20663171dc5
		summarizeBy: sum
		sourceColumn: change

		annotation SummarizationSetBy = Automatic

	column vwap
		dataType: string
		lineageTag: 8422f04a-bf17-4327-9f1e-9cfdbb017f97
		summarizeBy: none
		sourceColumn: vwap

		annotation SummarizationSetBy = Automatic

	column st
		dataType: string
		lineageTag: 27dc4fe8-006e-4aee-b21e-fb2cf3e40e21
		summarizeBy: none
		sourceColumn: st

		annotation SummarizationSetBy = Automatic

	column rsi
		dataType: string
		lineageTag: 4a80111b-bd9d-4891-a499-d20251284ec7
		summarizeBy: none
		sourceColumn: rsi

		annotation SummarizationSetBy = Automatic

	column AI
		dataType: string
		lineageTag: 9def57dd-1f63-4776-97c5-84c4994c71a2
		summarizeBy: none
		sourceColumn: AI

		annotation SummarizationSetBy = Automatic

	column EMA
		dataType: string
		lineageTag: 88319832-4657-4c74-8c9f-4d25e517cd9e
		summarizeBy: none
		sourceColumn: EMA

		annotation SummarizationSetBy = Automatic

	column 'Bollinger Bands'
		dataType: string
		lineageTag: b97d53c9-6684-4d6a-8794-8acbd01c8682
		summarizeBy: none
		sourceColumn: Bollinger Bands

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		lineageTag: 44b1f541-2d5d-4093-950b-850f2b787ff0
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 8ddfde57-1f30-456f-a5ae-f5e5c8b5c625
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	partition profile = m
		mode: import
		queryGroup: MainTables
		source =
				let
				    Source = Table.RenameColumns(Table.FromList(StockList) ,{{"Column1", "symbol"}}),
				    RunCompanyProfileApi = Table.AddColumn(Source, "RunCompanyProfile", each fn_RunAPI_Call("/v3/profile/", [symbol], "",  [apikey=apiKey])),
				    ExpandedRunCompanyProfileList = Table.ExpandListColumn(RunCompanyProfileApi, "RunCompanyProfile"),
				    ExpandedRunCompanyProfileRecord = Table.ExpandRecordColumn(ExpandedRunCompanyProfileList, "RunCompanyProfile", {"ceo", "companyName", "country", "currency", "exchange", "exchangeShortName", "fullTimeEmployees", "image", "industry", "isEtf", "mktCap", "price", "sector", "website"}, {"ceo", "companyName", "country", "currency", "exchange", "exchangeShortName", "fullTimeEmployees", "image", "industry", "isEtf", "mktCap", "price", "sector", "website"}),
				    #"Changed Type" = Table.TransformColumnTypes(ExpandedRunCompanyProfileRecord,{{"symbol", type text}, {"price", type number}, {"mktCap", Int64.Type}, {"companyName", type text}, {"exchange", type text}, {"exchangeShortName", type text}, {"industry", type text}, {"website", type text}, {"ceo", type text}, {"sector", type text}, {"fullTimeEmployees", Int64.Type}, {"image", type text}, {"isEtf", type logical},{"currency", type text},{"country", type text} }),
				    TransformedCEOName = Table.TransformColumns(#"Changed Type", {{"ceo", each Text.AfterDelimiter(_, ". "), type text}}),
				    TransfromedWesiteURL = Table.TransformColumns(TransformedCEOName, {{"website", each Text.AfterDelimiter(_, "//"), type text}}),
				    DuplicatedCompanyName = Table.DuplicateColumn(TransfromedWesiteURL, "companyName", "companyFullName"),
				    TransformedCompanyName = Table.TransformColumns(DuplicatedCompanyName, {{"companyName", each Text.BeforeDelimiter(Text.BeforeDelimiter(_," "),"."), type text }} ),
				    MergedWithPrice = Table.NestedJoin(TransformedCompanyName, {"symbol"}, price, {"symbol"}, "price.1", JoinKind.LeftOuter),
				    ExpandedPrice = Table.ExpandTableColumn(MergedWithPrice, "price.1", { "eps", "pe"}, { "eps", "pe"}),
				    #"Merged Queries" = Table.NestedJoin(ExpandedPrice, {"symbol"}, indicators, {"symbol"}, "indicators", JoinKind.LeftOuter),
				    #"Expanded indicators" = Table.ExpandTableColumn(#"Merged Queries", "indicators", {"52WeekHigh", "52WeekLow", "close", "change", "vwap", "st", "rsi", "AI", "EMA", "Bollinger Bands"}, {"52WeekHigh", "52WeekLow", "close", "change", "vwap", "st", "rsi", "AI", "EMA", "Bollinger Bands"})
				in
				    #"Expanded indicators"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

