[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "dimcustomer_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "CustomerKey", DestinationColumnName = "CustomerKey"], [SourceColumnName = "GeographyKey", DestinationColumnName = "GeographyKey"], [SourceColumnName = "CustomerAlternateKey", DestinationColumnName = "CustomerAlternateKey"], [SourceColumnName = "Title", DestinationColumnName = "Title"], [SourceColumnName = "FirstName", DestinationColumnName = "FirstName"], [SourceColumnName = "MiddleName", DestinationColumnName = "MiddleName"], [SourceColumnName = "LastName", DestinationColumnName = "LastName"], [SourceColumnName = "NameStyle", DestinationColumnName = "NameStyle"], [SourceColumnName = "BirthDate", DestinationColumnName = "BirthDate"], [SourceColumnName = "MaritalStatus", DestinationColumnName = "MaritalStatus"], [SourceColumnName = "Suffix", DestinationColumnName = "Suffix"], [SourceColumnName = "Gender", DestinationColumnName = "Gender"], [SourceColumnName = "EmailAddress", DestinationColumnName = "EmailAddress"], [SourceColumnName = "YearlyIncome", DestinationColumnName = "YearlyIncome"], [SourceColumnName = "TotalChildren", DestinationColumnName = "TotalChildren"], [SourceColumnName = "NumberChildrenAtHome", DestinationColumnName = "NumberChildrenAtHome"], [SourceColumnName = "EnglishEducation", DestinationColumnName = "EnglishEducation"], [SourceColumnName = "SpanishEducation", DestinationColumnName = "SpanishEducation"], [SourceColumnName = "FrenchEducation", DestinationColumnName = "FrenchEducation"], [SourceColumnName = "EnglishOccupation", DestinationColumnName = "EnglishOccupation"], [SourceColumnName = "SpanishOccupation", DestinationColumnName = "SpanishOccupation"], [SourceColumnName = "FrenchOccupation", DestinationColumnName = "FrenchOccupation"], [SourceColumnName = "HouseOwnerFlag", DestinationColumnName = "HouseOwnerFlag"], [SourceColumnName = "NumberCarsOwned", DestinationColumnName = "NumberCarsOwned"], [SourceColumnName = "AddressLine1", DestinationColumnName = "AddressLine1"], [SourceColumnName = "AddressLine2", DestinationColumnName = "AddressLine2"], [SourceColumnName = "Phone", DestinationColumnName = "Phone"], [SourceColumnName = "DateFirstPurchase", DestinationColumnName = "DateFirstPurchase"], [SourceColumnName = "CommuteDistance", DestinationColumnName = "CommuteDistance"], [SourceColumnName = "Inserted_at", DestinationColumnName = "Inserted_at"], [SourceColumnName = "Inserted_by", DestinationColumnName = "Inserted_by"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared dimcustomer = let
  Source = Sql.Databases("lhgom4gvucfepofzm6gm4lr2mm-gls3ow64xbcedgdpruhfcewe5y.datawarehouse.fabric.microsoft.com"),
  #"Navigation 1" = Source{[Name = "AdventureWorksDB"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Schema = "dbo", Item = "dimcustomer"]}[Data],
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Navigation 2", "Inserted_by", each "Dataflow"), {{"Inserted_by", type text}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Added custom", "Inserted_at", each DateTime.From(DateTime.LocalNow())), {{"Inserted_at", type datetime}}),
  #"Changed column type" = Table.TransformColumnTypes(#"Added custom 1", {{"DateFirstPurchase", type datetime}, {"BirthDate", type datetime}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "factinternetsales_DataDestination", IsNewTarget = false], Settings = [Kind = "Manual", AllowCreation = false, ColumnSettings = [Mappings = {[SourceColumnName = "ProductKey", DestinationColumnName = "ProductKey"], [SourceColumnName = "OrderDateKey", DestinationColumnName = "OrderDateKey"], [SourceColumnName = "DueDateKey", DestinationColumnName = "DueDateKey"], [SourceColumnName = "ShipDateKey", DestinationColumnName = "ShipDateKey"], [SourceColumnName = "CustomerKey", DestinationColumnName = "CustomerKey"], [SourceColumnName = "PromotionKey", DestinationColumnName = "PromotionKey"], [SourceColumnName = "CurrencyKey", DestinationColumnName = "CurrencyKey"], [SourceColumnName = "SalesTerritoryKey", DestinationColumnName = "SalesTerritoryKey"], [SourceColumnName = "SalesOrderNumber", DestinationColumnName = "SalesOrderNumber"], [SourceColumnName = "SalesOrderLineNumber", DestinationColumnName = "SalesOrderLineNumber"], [SourceColumnName = "RevisionNumber", DestinationColumnName = "RevisionNumber"], [SourceColumnName = "OrderQuantity", DestinationColumnName = "OrderQuantity"], [SourceColumnName = "UnitPrice", DestinationColumnName = "UnitPrice"], [SourceColumnName = "ExtendedAmount", DestinationColumnName = "ExtendedAmount"], [SourceColumnName = "UnitPriceDiscountPct", DestinationColumnName = "UnitPriceDiscountPct"], [SourceColumnName = "DiscountAmount", DestinationColumnName = "DiscountAmount"], [SourceColumnName = "ProductStandardCost", DestinationColumnName = "ProductStandardCost"], [SourceColumnName = "TotalProductCost", DestinationColumnName = "TotalProductCost"], [SourceColumnName = "SalesAmount", DestinationColumnName = "SalesAmount"], [SourceColumnName = "TaxAmt", DestinationColumnName = "TaxAmt"], [SourceColumnName = "Freight", DestinationColumnName = "Freight"], [SourceColumnName = "CarrierTrackingNumber", DestinationColumnName = "CarrierTrackingNumber"], [SourceColumnName = "CustomerPONumber", DestinationColumnName = "CustomerPONumber"], [SourceColumnName = "OrderDate", DestinationColumnName = "OrderDate"], [SourceColumnName = "DueDate", DestinationColumnName = "DueDate"], [SourceColumnName = "ShipDate", DestinationColumnName = "ShipDate"], [SourceColumnName = "Inserted_at", DestinationColumnName = "Inserted_at"], [SourceColumnName = "Inserted_by", DestinationColumnName = "Inserted_by"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared factinternetsales = let
  Source = Sql.Databases("lhgom4gvucfepofzm6gm4lr2mm-gls3ow64xbcedgdpruhfcewe5y.datawarehouse.fabric.microsoft.com"),
  #"Navigation 1" = Source{[Name = "AdventureWorksDB"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Schema = "dbo", Item = "factinternetsales"]}[Data],
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Navigation 2", "Inserted_by", each "Dataflow"), {{"Inserted_by", type text}}),
  #"Added custom 1" = Table.TransformColumnTypes(Table.AddColumn(#"Added custom", "Inserted_at", each DateTime.From(DateTime.LocalNow())), {{"Inserted_at", type datetime}})
in
  #"Added custom 1";
shared dimcustomer_DataDestination = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "d4d5e2ac-8606-409b-8e3f-9cce0d4738bc"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "634329b9-50ec-464a-a281-7a0be4a2697e"]}[Data],
  TableNavigation = Navigation_2{[Schema = "staging", Item = "dimcustomer"]}[Data]
in
  TableNavigation;
shared factinternetsales_DataDestination = let
  Pattern = Fabric.Warehouse([HierarchicalNavigation = null, CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "d4d5e2ac-8606-409b-8e3f-9cce0d4738bc"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "634329b9-50ec-464a-a281-7a0be4a2697e"]}[Data],
  TableNavigation = Navigation_2{[Schema = "staging", Item = "factinternetsales"]}[Data]
in
  TableNavigation;
