CREATE TABLE [dbo].[dimcustomer] (

	[CustomerKey] int NULL, 
	[GeographyKey] int NULL, 
	[CustomerAlternateKey] varchar(8000) NULL, 
	[Title] varchar(8000) NULL, 
	[FirstName] varchar(8000) NULL, 
	[MiddleName] varchar(8000) NULL, 
	[LastName] varchar(8000) NULL, 
	[NameStyle] bit NULL, 
	[BirthDate] datetime2(6) NULL, 
	[MaritalStatus] varchar(8000) NULL, 
	[Suffix] varchar(8000) NULL, 
	[Gender] varchar(8000) NULL, 
	[EmailAddress] varchar(8000) NULL, 
	[YearlyIncome] decimal(8,2) NULL, 
	[TotalChildren] smallint NULL, 
	[NumberChildrenAtHome] smallint NULL, 
	[EnglishEducation] varchar(8000) NULL, 
	[SpanishEducation] varchar(8000) NULL, 
	[FrenchEducation] varchar(8000) NULL, 
	[EnglishOccupation] varchar(8000) NULL, 
	[SpanishOccupation] varchar(8000) NULL, 
	[FrenchOccupation] varchar(8000) NULL, 
	[HouseOwnerFlag] varchar(8000) NULL, 
	[NumberCarsOwned] smallint NULL, 
	[AddressLine1] varchar(8000) NULL, 
	[AddressLine2] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[DateFirstPurchase] datetime2(6) NULL, 
	[CommuteDistance] varchar(8000) NULL
);