table Main_Refresh
	lineageTag: 9d1a6bc0-a946-4c14-968c-a95a8a293b4b

	column DateTime
		dataType: string
		lineageTag: beb58e10-53d3-4132-b6e5-cebbf7c45b49
		summarizeBy: none
		sourceColumn: DateTime

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9cdb03ad-a17a-4277-93e5-9bc6eb7111e0
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: e287bb65-f5a1-4a01-9fe2-69c96128c2c9
			defaultHierarchy: LocalDateTable_b34a2556-8dbc-4c6f-8482-e45f21e23407.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Main_Refresh = m
		mode: import
		source =
				let
				    Source = DateTime.FixedLocalNow(),
				    #"Converted to Table" = #table(1, {{Source}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "DateTime"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "DateTime", "DateTime - Copy"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Duplicated Column",{{"DateTime - Copy", type date}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"DateTime - Copy", "Date"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

