table Mon_Sort_2
	lineageTag: a82aa917-4218-4841-a421-c283b322d1f0

	column Mon/Yr
		dataType: string
		lineageTag: 281a1ab8-a1d0-42d1-8f89-dc2e62cfb5b3
		summarizeBy: none
		sourceColumn: Mon/Yr
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: ad73819e-01ba-459e-9543-1d7e887976ca
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Mon
		dataType: string
		lineageTag: 75580a8c-2c72-4cc8-a443-ee44f009529b
		summarizeBy: none
		sourceColumn: Mon

		annotation SummarizationSetBy = Automatic

	partition Mon_Sort_2 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Contractual Capacity.xlsx"), null, true),
				    Mon_Sort_2_Table = Source{[Item="Mon_Sort_2",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Mon_Sort_2_Table,{{"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

