table Month_Level_Cvg
	lineageTag: a83027d6-4e74-4996-be6a-4209b8951fc2

	measure LyVal_new =
			
			CALCULATE(
			    SUMX(
			        FILTER(
			            Month_Level_Cvg,
			            Month_Level_Cvg[G-Sales District (Ship-To)] IN VALUES(Month_Level_Cvg[G-Sales District (Ship-To)])
			        ),
			        Month_Level_Cvg[22/23]
			    )
			)
		formatString: 0.0
		lineageTag: 14e54845-3fb0-4353-8f6e-6344efb895be

	measure LYValueYTD_New = ```
			
			IF (
			    SELECTEDVALUE ( Month_Sort[Month] ) = "LY", 
			    CALCULATE ( SUMX (FILTER (Year_Level_Cvg,
			            Year_Level_Cvg[G-Sales District (Ship-To)] = SELECTEDVALUE ( Market[Market (Key)] )), Year_Level_Cvg[22/23]
			       )    )
			)
			
			```
		lineageTag: 45dae743-1035-4661-9d8b-f855d6ee9078

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ValueYTD_New = ```
			
			IF (
			    SELECTEDVALUE ( Month_Sort[Month] ) = "YTD", 
			    CALCULATE( VALUES(Year_Level_Cvg[23/24]),
			
			            FILTER ( Year_Level_Cvg, Year_Level_Cvg[G-Sales District (Ship-To)] = SELECTEDVALUE(Market[Market (Key)] )
			        )
			))
			```
		lineageTag: f68a804f-b3b5-4be0-9ba6-aaac79785bf7

	measure YTD_New =
			
			CALCULATE (
			    SUMX (
			        FILTER (
			            Month_Level_Cvg,
			            Month_Level_Cvg[G-Sales District (Ship-To)] = SELECTEDVALUE(Month_Level_Cvg[G-Sales District (Ship-To)])
			        ),
			        Month_Level_Cvg[23/24]
			    )
			)
		lineageTag: aa92768b-7233-4e35-9b7e-40313f7ec690

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'G-Sales District (Ship-To)'
		dataType: string
		lineageTag: 6108fa89-7b6b-4b78-901f-17e9c46c95e7
		summarizeBy: none
		sourceColumn: G-Sales District (Ship-To)

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 0484c4cd-911f-46af-9671-a7c860bb163f
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 22/23
		dataType: double
		lineageTag: b9aba8da-5e2e-4c67-9814-668e687c0127
		summarizeBy: sum
		sourceColumn: 22/23

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 23/24
		dataType: double
		lineageTag: 2f0730e1-955d-4f0e-a10a-bd2fb86fb228
		summarizeBy: sum
		sourceColumn: 23/24

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Month_Level_Cvg = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Stk Cvg_Weekly Files\Mapping"),
				    #"Filtered Hidden Files2" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function2" = Table.AddColumn(#"Filtered Hidden Files2", "Transform File (20)", each #"Transform File (20)"([Content])),
				    #"Renamed Columns2" = Table.RenameColumns(#"Invoke Custom Function2", {"Name", "Source.Name"}),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Renamed Columns2", {"Source.Name", "Transform File (20)"}),
				    #"Expanded Transform File (20)" = Table.ExpandTableColumn(#"Removed Other Columns2", "Transform File (20)", {"G-Sales District (Ship-To)", "Month", "22/23", "23/24"}, {"Transform File (20).G-Sales District (Ship-To)", "Transform File (20).Month", "Transform File (20).22/23", "Transform File (20).23/24"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Transform File (20)",{{"Transform File (20).G-Sales District (Ship-To)", "G-Sales District (Ship-To)"}, {"Transform File (20).Month", "Month"}, {"Transform File (20).22/23", "22/23"}, {"Transform File (20).23/24", "23/24"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Source.Name", type text}, {"G-Sales District (Ship-To)", type text}, {"Month", type text}, {"22/23", type number}, {"23/24", type number}}),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Changed Type2", each [Attributes]?[Hidden]? <> true),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Hidden Files1",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

