table Str_Loc
	lineageTag: c1faa105-b152-4b06-b27e-b52f400f507c

	column 'Storage Loc.'
		dataType: string
		lineageTag: 5918840d-df02-47b2-bd2a-8069dd18ca77
		summarizeBy: none
		sourceColumn: Storage Loc.

		annotation SummarizationSetBy = Automatic

	column 'Desc.'
		dataType: string
		lineageTag: 8c315bad-f95f-4507-b56f-d6f1ea62562b
		summarizeBy: none
		sourceColumn: Desc.

		annotation SummarizationSetBy = Automatic

	column 'When to use?'
		dataType: string
		lineageTag: 5cf47e00-32d7-4e11-892e-e55ba575c27b
		summarizeBy: none
		sourceColumn: When to use?

		annotation SummarizationSetBy = Automatic

	column 'Short Name'
		dataType: string
		lineageTag: fe335992-374e-46d3-b2e2-e4abbec13300
		summarizeBy: none
		sourceColumn: Short Name

		annotation SummarizationSetBy = Automatic

	partition Str_Loc = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\sharasara1\OneDrive - Ferrero Ecosystem\Desktop\GAC DB DATA\Onemasterdata.xlsx"), null, true),
				    Str_Loc_Table = Source{[Item="Str_Loc",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Str_Loc_Table,{{"Storage Loc.", type text}, {"Desc.", type text}, {"When to use?", type text}, {"Short Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

